name: Python Test

on:
  push:
    branches: ["main"]
    paths-ignore: ["README.md", "docs"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["README.md", "docs"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --all-extras
      - name: Pyright
        run: |
          poetry run pyright .
      - name: Create Test data
        run: poetry run python -m tests.create_test_data
      - name: Test with pytest
        run: poetry run pytest tests
